### ISSUE TITLE
Problem with default directory to run project

### ISSUE THREAD

**Issue by oemartinez2018** [eXistenZNL/Docker-Webstack#22]
The default directory to work with the project is /www/public not /www

**Comment by eXistenZNL** [comment]
Hi @oemartinez2018, sorry for the (very) late response.

The dir is indeed /www. Did you encounter a problem with that? Perhaps the documentation that states otherwise?

Please let me know so I can fix it.

**Comment by oemartinez2018** [comment]
Nope, everything works perfectly just update in the documentation that the default working directory is /www/public that works for me, /var/www didn't work

**Comment by eXistenZNL** [comment]
Yep I noticed my mistake, must have glanced over it 10.000 times! Updating as we speak, thanks again for mentioning this!

**Comment by eXistenZNL** [comment]
Fixed with [this commit](https://github.com/eXistenZNL/Docker-Webstack/commit/6b6294790b88dc9ed00a9c2aad5302ed10b3b18e), closing this issue. Cheers!

**Comment by eXistenZNL** [comment]
Ah I understand. The reason for this is that most - if not all - frameworks (like Laravel, Symfony, etc.) bring their own public folder that is part of the application code. Copying such a framework to /www wil thus result in /www/public being created automatically, thus resulting in a situation where everything works.

To mimick this behavior when using single or custom PHP scripts, copy them to /www/public indeed.

I will add some documentation regarding this to the README.md file.

**Comment by eXistenZNL** [comment]
Fixed with [this commit](https://github.com/eXistenZNL/Docker-Webstack/commit/307a0c3da709824722d0893c84f0cdda3e4313e4), closing the issue. Cheers!
