### ISSUE TITLE
How come composer is not included by default?

### ISSUE THREAD

**Issue by simplenotezy** [eXistenZNL/Docker-Webstack#26]
Thanks for a nice Dockerfile - however, I wonder, why is composer not installed by default?

And how would you manage php artisan migrate?

**Comment by pimjansen** [comment]
Composer is a package manager for PHP. Why should this be included in a PHP installation? When you install PHP itself composer is also not included.

You can easily just add it as extra layer?

**Comment by eXistenZNL** [comment]
Hi!

Composer is included in my [Buillder image](https://github.com/eXistenZNL/Docker-Builder), which can be used in CI to install your dependencies and then build a Webstack container with everything in it :)

Hope this helps, closing the issue. If not, please reply :+1:
