### ISSUE TITLE
Running for +200s

### ISSUE THREAD

**Issue by simplenotezy** [eXistenZNL/Docker-Webstack#27]
I tried following your example, with this Dockerfile:

```
FROM existenz/webstack:7.4
COPY --chown=php:nginx . /www


RUN find /www -type d -exec chmod -R 555 {} \; \
    && find /www -type f -exec chmod -R 444 {} \; \
    && find /www/var -type d -exec chmod -R 755 {} \; \
    && find /www/var -type f -exec chmod -R 644 {} \; \
    && apk -U --no-cache add \
    php7-ctype \
    php7-json \
    php7-mbstring

```
However, after 200 seconds it's still stuck on the RUN command.

Is this expected?

**Comment by eXistenZNL** [comment]
Hi,

this can be the case if you copy over lots and lots of files which then are mode changed with chmod. You can try disabling those commands to see if that fixes the 200 seconds delay. It is however probably a good idea to make sure that some directories have write permissions, like the var directory, or your framework cannot write anything to the container.

Hope this helps, closing the issue. If not, please leave a reply.
