### ISSUE TITLE
Install php extensions

### ISSUE THREAD

**Issue by drequivalent** [eXistenZNL/Docker-Webstack#29]
How do I go about installing PHP/Zend extensions? Like this one:
https://github.com/krakjoe/tombs

**Comment by eXistenZNL** [comment]
You could probably compile that extension, that's also mostly how the official PHP image works. That container ships with all the tools on board to compile extensions, it is however pretty slow when baking your container and probably bigger too.

Hope this helps, closing the issue. If not, please leave a reply.
