### ISSUE TITLE
How to install php8-pecl-swoole

### ISSUE THREAD

**Issue by pawan-khade** [eXistenZNL/Docker-Webstack#31]
Dear sir,
I want to integrate swoole octane with this docker file how to do that with minimum size of image.

Regards

**Comment by eXistenZNL** [comment]
You could probably compile that extension, that's also mostly how the official PHP image works. That container ships with all the tools on board to compile extensions, it is however pretty slow when baking your container and probably bigger too.

Hope this helps, closing the issue. If not, please leave a reply.
