### ISSUE TITLE
These images do not run on arm architecture even using buildx

### ISSUE THREAD

**Issue by pawan-khade** [eXistenZNL/Docker-Webstack#36]
These images do not run on arm architecture even using buildx.

How to run them?

**Comment by pawan-khade** [comment]
docker buildx build --platform linux/arm64 .
[+] Building 3.1s (6/10)                                                                                                                                                                      
 => [internal] load build definition from Dockerfile                                                                                                                                     0.1s
 => => transferring dockerfile: 32B                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.1s
 => => transferring context: 34B                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/existenz/webstack:8.0                                                                                                                         1.2s
 => CANCELED [internal] load build context                                                                                                                                               1.7s
 => => transferring context: 14.87MB                                                                                                                                                     1.7s
 => CACHED [1/6] FROM docker.io/existenz/webstack:8.0@sha256:cf9135fd770052f975342c6a10afaaa540ec6ba08a3302d85ce32a880612bb6a                                                            0.0s
 => ERROR [2/6] RUN apk add --no-cache php8-openssl php8-session php8 php8-tokenizer php8-pdo php8-pdo_mysql php8-zip php8-xml php8-simplexml php8-fileinfo php8-xmlreader php8-xmlwrit  1.7s
------                                                                                                                                                                                        
 > [2/6] RUN apk add --no-cache php8-openssl php8-session php8 php8-tokenizer php8-pdo php8-pdo_mysql php8-zip php8-xml php8-simplexml php8-fileinfo php8-xmlreader php8-xmlwriter:
#0 1.462 exec /bin/sh: exec format error
------
ERROR: failed to solve: executor failed running [/bin/sh -c apk add --no-cache php8-openssl php8-session php8 php8-tokenizer php8-pdo php8-pdo_mysql php8-zip php8-xml php8-simplexml php8-fileinfo php8-xmlreader php8-xmlwriter]: exit code: 1

**Comment by eXistenZNL** [comment]
@pawan-khade Hi and thanks for asking!

Currently these images are only baked for x86, however with the new upcoming MacBooks all running on ARM I realized a few months ago that it's probably time to bake them for ARM as well. In the past the only ARM chipsets that were really used were Raspberry Pi's and nobody seem to run my containers on them.

So, this is on my todo-list, but currently only X86 is supported.

I'll keep this issue open and update you on any progress. Expect to see some within a week or two.

**Comment by GeNyaa** [comment]
As a workaround, you can run the containers on MacBooks with the following:

```
FROM --platform=linux/amd64 existenz/webstack:8.1
```

Not ideal performance-wise, but it works.

**Comment by eXistenZNL** [comment]
Thanks for the helpful insight @GeNyaa :+1:

**Comment by eXistenZNL** [comment]
All variants of the container are now also available for arm64 architecture as can be seen [here](https://hub.docker.com/repository/docker/existenz/webstack/tags?page=1&ordering=last_updated) :tada:.

Just remember that building a ARM based container locally and then pushing to some random container hosting service will probably not work for the very same reason, namely that the architecture of the container and the host will differ.
