### ISSUE TITLE
PHP 8.1 image not working

### ISSUE THREAD

**Issue by Kirill-SDS** [eXistenZNL/Docker-Webstack#47]
I did docker run you image and "php -v" in it 

and somehow PHP not found

**Comment by saundersdigital** [comment]
@Kirill-SDS  If you are using the 8.1 image, you should run `php81 -v` ... You could also run something like `ln -s /usr/bin/php81 /usr/bin/php` in your `Dockerfile` to create a link from the php81 binary to php

**Comment by eXistenZNL** [comment]
The answer given by @saundersdigital is indeed how it is intended.

Also do not forget to install the `php81` package to get the CLI, by default the webstack comes without the CLI installed.
