### ISSUE TITLE
exec format error on arm image

### ISSUE THREAD

**Issue by cp-fabian-pittroff** [eXistenZNL/Docker-Webstack#48]
the docker image is not supported by arm servers (tested on hetzner arm vms). The init script from s6 seems to be the problem.
The s6 init step inside the Makefile, only downloads the amd64 version. On mac with m1/2 chips, it seems to work because of the rosetta implementation.

I added this section to my own Dockerfile to fix the issue:

```dockerfile
FROM existenz/webstack:8.2-edge
ARG TARGETPLATFORM #not sure if it is needed

RUN case "${TARGETPLATFORM}" in \
    "linux/amd64") \
        wget -P /tmp https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz && \
        gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C / \
        ;; \
    "linux/arm64") \
        wget -P /tmp https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-arm.tar.gz && \
        gunzip -c /tmp/s6-overlay-arm.tar.gz | tar -xf - -C / \
        ;; \
    esac; \
    rm -rf /tmp/*;
```

If you want, I can create a PR to move the s6 init download to the Dockerfile and allow to override the s6 version with an ARG.

**Comment by eXistenZNL** [comment]
Cool cool cool I will make sure to add this soon, thanks for finding out!

**Comment by eXistenZNL** [comment]
@cp-fabian-pittroff currently I am pretty busy with lots of stuff, so I didn't find the time yet to fix this. I hope to do this in the coming weeks but if you can create a PR instead, that would be really helpful :+1: thanks a ton!
