### ISSUE TITLE
ln: /usr/bin/php: File exists

### ISSUE THREAD

**Issue by eXistenZNL** [eXistenZNL/Docker-Webstack#54]
## Issue

When building the container, I run into the error `ln: /usr/bin/php: File exists`. This was not the case before yesterday! What is going on?

## Reason

As of Jan 18th 2024 the underlying Alpine Linux versions got bumped for the 8.1 and 8.2 versions of the webstack. If you are installing the PHP CLI package (`php81` or `php82`) and were making a symlink before (e.g. `ln -s /usr/bin/php81 /usr/bin/php`) this is now no longer needed as this symlink is provided by the package. Trying to do so will give the mentioned error.

## Solution

Simply remove the creation of the symlink from your Dockerfile. Everything should work as before.

**Comment by eXistenZNL** [comment]
Closing, as this has been here long enough now and nobody seems to have run into this issue.

**Comment by dustinc** [comment]
@eXistenZNL just an FYI

> (e.g. ln -s /usr/bin/php81 /usr/bin/php) this is now no longer needed as this symlink is provided by the package. 

This does not seem to be the case for `php83`, as I did have to add `ln -s /usr/bin/php83 /usr/bin/php` to my Dockerfile to get `php` command.
